targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/domain/entities/*.dart
            - lib/infrastructures/**/dto/*.dart
      json_serializable:
        generate_for:
          include:
            - lib/domain/entities/*.dart
            - lib/infrastructures/**/dto/*.dart
        options:
          any_map: true
          explicit_to_json: true
