name: upload codecov on mac12 for dev
on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: check flutter source
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Record Status
        run: flutter doctor
      - name: Create language
        run: flutter gen-l10n
      - name: Install packages
        run: flutter pub get
      - name: Run build_runner
        run: flutter pub run build_runner build
      - name: Linter
        run: flutter analyze
      - name: Test
        run: flutter test --coverage --coverage-path=~/coverage/lcov.info
      - uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ~/coverage/lcov.info
          fail_ci_if_error: true