name: analyze and test code before pull request for dev
on:
  pull_request:
    branches:
      - dev
jobs:
  test:
    name: check flutter source
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Record Status
        run: flutter doctor
